version: '3'

services:
  db:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: niceactionstacker
      POSTGRES_PASSWORD: niceactionstacker
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin4:
    image: dpage/pgadmin4:3.3
    container_name: pgadmin4
    ports:
      - 80:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always

  java:
    image: sup0ry0jodoi/nice-action-stacker:0.0.1
    build:
      context: .
      dockerfile: ./docker/java/Dockerfile
      args:
        - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    command: java -jar niceactionstacker-*.jar
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/nice_action_stacker"
    ports:
      - 8080:8080
