spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nice_action_stacker
    username: niceactionstacker
    password: niceactionstacker

slack:
  baseUrl: https://ca-black.slack.com/archives/
  bot:
    token:
    id: "@D019RS0MKTP"

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
